# Generated by Django 3.2.15 on 2022-08-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='species',
            options={'verbose_name_plural': 'species'},
        ),
        migrations.AddField(
            model_name='detection',
            name='status',
            field=models.CharField(choices=[('automated_detection_only', 'Automated detection only'), ('reviewed_valid', 'Human reviewed as valid'), ('reviewed_invalid', 'Human reviewed as invalid')], default='automated_detection_only', max_length=30),
        ),
        migrations.AddField(
            model_name='recording',
            name='analyze_status',
            field=models.CharField(choices=[('analyzed', 'Analyzed'), ('pending', 'Pending'), ('ignored', 'Ignored')], default='pending', max_length=30),
        ),
    ]
