# Generated by Django 3.2.15 on 2022-08-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0002_auto_20220823_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='acquistion_type',
            field=models.CharField(choices=[('manual', 'Manual recording'), ('automated', 'Automated recording'), ('third_party', 'Third-party recording'), ('unknown', 'Unknown'), ('other', 'Other')], default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='recording',
            name='has_accurate_location',
            field=models.BooleanField(default=False, help_text='User confirmed that location data is accurate.'),
        ),
    ]
