# Generated by Django 3.2.15 on 2022-08-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0007_alter_recording_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recording',
            name='file',
        ),
    ]
