# Generated by Django 3.2.15 on 2022-08-27 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0010_alter_recording_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='extracted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detection',
            name='extracted_path',
            field=models.FilePathField(blank=True, null=True, path='/home/pi/birdnetlib-listener/recordings_extracted'),
        ),
        migrations.AlterField(
            model_name='recording',
            name='filepath',
            field=models.FilePathField(blank=True, null=True, path='/home/pi/birdnetlib-listener/recordings_analyzed'),
        ),
    ]
