# Generated by Django 3.2.15 on 2022-08-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0011_auto_20220827_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='detection',
            name='extracted_file',
            field=models.FileField(blank=True, null=True, upload_to='extracted/%Y/%m/%d/'),
        ),
    ]
