# Generated by Django 3.2.15 on 2022-08-29 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0012_detection_extracted_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detection',
            name='extracted_path',
        ),
    ]
