# Generated by Django 3.2.15 on 2023-11-16 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0013_remove_detection_extracted_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='filepath',
            field=models.FilePathField(blank=True, null=True, path='/usr/audio/analyzed'),
        ),
        migrations.CreateModel(
            name='SpeciesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='species_images')),
                ('source_id', models.CharField(blank=True, help_text='The source ID for Flickr, or any other source.', max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to skip this image.')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordings.species')),
            ],
        ),
    ]
