version: "3.8"

services:
  web:
    build:
      context: ./server
      dockerfile: Dockerfile.rpi
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    volumes:
      - ./server/:/usr/src/app/
      - ./audio/inbox/:/usr/audio/incoming/
      - ./audio/post_analyze/:/usr/audio/analyzed/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
