# Generated by Django 3.2.15 on 2022-08-24 01:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0003_auto_20220823_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('analyzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordings.analyzer')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordings.recording')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detection',
            name='analysis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recordings.analysis'),
            preserve_default=False,
        ),
    ]
