# Generated by Django 3.2.15 on 2022-08-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0004_auto_20220824_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyzer',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analyzer',
            name='version',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
