# Generated by Django 3.2.15 on 2022-08-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordings', '0008_remove_recording_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name', max_length=50)),
                ('notification_type', models.CharField(choices=[('apprise', 'Apprise'), ('other', 'Other')], default='apprise', max_length=50)),
                ('detection_type', models.CharField(choices=[('all', 'All detections'), ('new_all_time', 'New species detected'), ('new_daily', 'New species for today')], default='new_daily', max_length=50)),
                ('apprise_string', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
