FROM python:3.9
WORKDIR /usr/src/app

RUN python -m pip install --upgrade pip

COPY ./bin/tflite_runtime-2.6.0-cp39-cp39-linux_aarch64.whl /usr/src/app/

RUN apt-get update; apt-get install -y inotify-tools ffmpeg libsqlite3-mod-spatialite gdal-bin

COPY ./requirements.rpi.txt .
RUN pip install -r requirements.rpi.txt

ADD . .