FROM python:3.9
WORKDIR /usr/src/app

RUN python -m pip install --upgrade pip

RUN apt-get update; apt-get install -y inotify-tools ffmpeg libsqlite3-mod-spatialite gdal-bin

COPY ./requirements.macos.intel.txt .
RUN pip install -r requirements.macos.intel.txt


ADD . .